import Link from "next/link";
import { createClient } from "@repo/supabase/server";
import { requireAdmin } from "../_lib/require-admin";
export const dynamic = "force-dynamic";
interface PageProps { searchParams: Promise<{ q?: string }> }
export default async function ApartmentsPage({ searchParams }: PageProps) {
  await requireAdmin(); const { q = "" } = await searchParams; const supabase = await createClient(); let query = supabase.from("apartments").select("id, name, city, status, is_verified, monthly_rent").is("deleted_at", null).order("created_at", { ascending: false }).limit(50); if (q.trim()) query = query.ilike("name", `%${q.trim()}%`); const { data: apartments, error } = await query;
  return <div className="mx-auto w-full max-w-7xl space-y-5 p-4"><div><h1 className="font-nunito text-3xl font-bold">Apartments</h1><p className="mt-1 text-sm text-muted-foreground">Review published and pending property records.</p></div><form className="flex gap-2"><input name="q" defaultValue={q} placeholder="Search apartments" className="h-10 rounded-xl border border-border bg-card px-3 text-sm focus:outline-none focus:ring-2 focus-visible:ring-primary/15"/><button className="rounded-xl bg-primary px-4 text-sm font-semibold text-white">Search</button></form>{error ? <p role="alert" className="text-sm text-danger">Unable to load apartments.</p> : <div className="overflow-x-auto rounded-xl border border-border"><table className="w-full text-left text-sm"><thead className="bg-muted text-[11px] uppercase tracking-wider text-muted-foreground"><tr><th className="p-3">Apartment</th><th className="p-3">Status</th><th className="p-3">Verification</th><th className="p-3"><span className="sr-only">Details</span></th></tr></thead><tbody>{apartments?.map((apartment) => <tr key={apartment.id} className="border-t border-border"><td className="p-3"><p className="font-medium">{apartment.name}</p><p className="text-muted-foreground">{apartment.city}</p></td><td className="p-3 capitalize">{apartment.status}</td><td className="p-3">{apartment.is_verified ? "Verified" : "Unverified"}</td><td className="p-3 text-right"><Link href={`/admin/apartments/${apartment.id}`} className="font-semibold text-primary hover:underline">View</Link></td></tr>)}</tbody></table></div>}</div>;
}
