export type Property = {
  id: string;
  name: string;
  description: string | null;
  monthly_rent: number;
  security_deposit: number | null;
  advance_rent: number | null;
  type: string | null;
  street_address: string | null;
  barangay: string | null;
  city: string | null;
  province: string | null;
  zip_code: number | null;
  status: string;
  average_rating: number;
  no_ratings: number;
  no_bedrooms: number | null;
  no_bathrooms: number | null;
  area_sqm: number | null;
  max_occupants: number | null;
  furnished_type: string | null;
  floor_level: string | null;
  lease_duration: string | null;
  latitude: number | null;
  longitude: number | null;
  amenities: string[];
  thumbnail: string;
  lease_agreement_url?: string | null;
};
